export const jobs = [
  {
    id: "1",
    title: "Software Engineer",
    company: "Tech Solutions Inc.",
    location: "San Francisco, CA",
    employment_type: "Full-time",
    posted_date: "2024-09-01",
    description: "Develop and maintain web applications.",
    experience_level: "Mid-Senior",
    salary_range: "$100k - $120k",
    industry: "Information Technology",
    applicants: 45,
    remote: true,
    url: "https://www.linkedin.com/jobs/view/1"
  },
  {
    id: "2",
    title: "Product Manager",
    company: "Innovatech Corp.",
    location: "New York, NY",
    employment_type: "Full-time",
    posted_date: "2024-08-30",
    description: "Manage the development of new products.",
    experience_level: "Senior",
    salary_range: "$130k - $150k",
    industry: "Software",
    applicants: 60,
    remote: false,
    url: "https://www.linkedin.com/jobs/view/2"
  },
  {
    id: "3",
    title: "Data Analyst",
    company: "DataPro Analytics",
    location: "Chicago, IL",
    employment_type: "Contract",
    posted_date: "2024-08-28",
    description: "Analyze large datasets to drive decision making.",
    experience_level: "Entry-Level",
    salary_range: "$70k - $80k",
    industry: "Data Analytics",
    applicants: 20,
    remote: true,
    url: "https://www.linkedin.com/jobs/view/3"
  },
  {
    id: "4",
    title: "UX/UI Designer",
    company: "Creative Minds",
    location: "Austin, TX",
    employment_type: "Full-time",
    posted_date: "2024-08-25",
    description: "Design intuitive user interfaces for web and mobile apps.",
    experience_level: "Mid-Level",
    salary_range: "$90k - $110k",
    industry: "Design",
    applicants: 35,
    remote: false,
    url: "https://www.linkedin.com/jobs/view/4"
  },
  {
    id: "5",
    title: "Marketing Coordinator",
    company: "Growth Hacks LLC",
    location: "Los Angeles, CA",
    employment_type: "Part-time",
    posted_date: "2024-08-24",
    description: "Coordinate marketing campaigns and strategies.",
    experience_level: "Entry-Level",
    salary_range: "$50k - $60k",
    industry: "Marketing",
    applicants: 25,
    remote: true,
    url: "https://www.linkedin.com/jobs/view/5"
  },
  {
    id: "6",
    title: "DevOps Engineer",
    company: "CloudNet Solutions",
    location: "Seattle, WA",
    employment_type: "Full-time",
    posted_date: "2024-08-23",
    description: "Manage cloud infrastructure and automation pipelines.",
    experience_level: "Mid-Senior",
    salary_range: "$120k - $140k",
    industry: "Cloud Computing",
    applicants: 50,
    remote: true,
    url: "https://www.linkedin.com/jobs/view/6"
  },
  {
    id: "7",
    title: "HR Specialist",
    company: "People First Co.",
    location: "Boston, MA",
    employment_type: "Full-time",
    posted_date: "2024-08-22",
    description: "Handle recruitment, employee relations, and benefits.",
    experience_level: "Mid-Level",
    salary_range: "$60k - $80k",
    industry: "Human Resources",
    applicants: 30,
    remote: false,
    url: "https://www.linkedin.com/jobs/view/7"
  },
  {
    id: "8",
    title: "Sales Manager",
    company: "Retail Masters",
    location: "Houston, TX",
    employment_type: "Full-time",
    posted_date: "2024-08-20",
    description: "Oversee sales strategies and manage the sales team.",
    experience_level: "Senior",
    salary_range: "$110k - $130k",
    industry: "Retail",
    applicants: 40,
    remote: false,
    url: "https://www.linkedin.com/jobs/view/8"
  },
  {
    id: "9",
    title: "Customer Support Specialist",
    company: "HelpDesk Inc.",
    location: "Remote",
    employment_type: "Full-time",
    posted_date: "2024-08-18",
    description: "Provide technical support and troubleshooting for customers.",
    experience_level: "Entry-Level",
    salary_range: "$40k - $50k",
    industry: "Customer Service",
    applicants: 55,
    remote: true,
    url: "https://www.linkedin.com/jobs/view/9"
  },
  {
    id: "10",
    title: "Financial Analyst",
    company: "InvestCo Advisors",
    location: "Miami, FL",
    employment_type: "Full-time",
    posted_date: "2024-08-15",
    description: "Analyze financial data to advise on business decisions.",
    experience_level: "Mid-Level",
    salary_range: "$80k - $100k",
    industry: "Finance",
    applicants: 25,
    remote: false,
    url: "https://www.linkedin.com/jobs/view/10"
  },
  {
    id: "11",
    title: "Cybersecurity Specialist",
    company: "SecureNet",
    location: "Denver, CO",
    employment_type: "Full-time",
    posted_date: "2024-08-10",
    description: "Ensure the security of company networks and systems.",
    experience_level: "Mid-Senior",
    salary_range: "$110k - $130k",
    industry: "Cybersecurity",
    applicants: 40,
    remote: true,
    url: "https://www.linkedin.com/jobs/view/11"
  },
  {
    id: "12",
    title: "Project Manager",
    company: "BuildTech",
    location: "Atlanta, GA",
    employment_type: "Contract",
    posted_date: "2024-08-05",
    description: "Manage construction projects from inception to completion.",
    experience_level: "Senior",
    salary_range: "$90k - $110k",
    industry: "Construction",
    applicants: 35,
    remote: false,
    url: "https://www.linkedin.com/jobs/view/12"
  }
];
